export const hudlRoles = [
  {
    department: 'Marketing Ops',
    title: 'Marketing Technology Specialist',
    knowledge: '',
    communication: '',
    gsd: '',
    innovation: '',
    complexity: '',
    ownership: '',
    impact: '',
    score: '',
    level: 3
  },
  {
    department: 'Marketing Ops',
    title: 'Project Manager',
    knowledge: 3,
    communication: 5,
    gsd: 4,
    innovation: 4,
    complexity: 3,
    ownership: 4,
    impact: 4,
    score: 31,
    level: 4
  },
  {
    department: 'Corporate Operations',
    title: 'Sr. Specialst, Internal Operations',
    knowledge: 3,
    communication: 5,
    gsd: 3,
    innovation: 3,
    complexity: 4,
    ownership: 3,
    impact: 4,
    score: 29,
    level: 4
  },
  {
    department: 'Corporate Operations',
    title: 'Travel & Events Specialist',
    knowledge: 3,
    communication: 5,
    gsd: 3,
    innovation: 2,
    complexity: 3,
    ownership: 3,
    impact: 4,
    score: 27,
    level: 3
  },
  {
    department: 'Corporate Operations',
    title: 'Corporate Operations Manager',
    knowledge: 3,
    communication: 5,
    gsd: 5,
    innovation: 4,
    complexity: 4,
    ownership: 4,
    impact: 5,
    score: 35,
    level: 5
  },
  {
    department: 'Corporate Operations',
    title: 'Travel & Events Coordinator',
    knowledge: 3,
    communication: 3,
    gsd: 3,
    innovation: 2,
    complexity: 2,
    ownership: 3,
    impact: 3,
    score: 22,
    level: 2
  },
  {
    department: 'Customer Solutions',
    title: 'Implementation Manager',
    knowledge: 4,
    communication: 4,
    gsd: 4,
    innovation: 4,
    complexity: 4,
    ownership: 3,
    impact: 3,
    score: 29,
    level: 4
  },
  {
    department: 'Customer Solutions',
    title: 'Sr. Implementation Manager',
    knowledge: 4,
    communication: 5,
    gsd: 5,
    innovation: 5,
    complexity: 5,
    ownership: 4,
    impact: 4,
    score: 36,
    level: 5
  },
  {
    department: 'Customer Solutions',
    title: 'Sr. Elite Education Strategist',
    knowledge: 5,
    communication: 5,
    gsd: 4,
    innovation: 4,
    complexity: 4,
    ownership: 4,
    impact: 4,
    score: 34,
    level: 5
  },
  {
    department: 'Customer Solutions',
    title: 'Sr. Manager, Elite Education',
    knowledge: 5,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 4,
    ownership: 5,
    impact: 4,
    score: 38,
    level: 6
  },
  {
    department: 'Customer Solutions',
    title: 'Sr. Manager, Customer Solutions',
    knowledge: 5,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 4,
    ownership: 6,
    impact: 4,
    score: 39,
    level: 6
  },
  {
    department: 'Customer Solutions',
    title: 'Sr. Technical Consultant',
    knowledge: 5,
    communication: 5,
    gsd: 5,
    innovation: 5,
    complexity: 4,
    ownership: 5,
    impact: 4,
    score: 37,
    level: 5
  },
  {
    department: 'Customer Solutions',
    title: 'Sr. Strategic Consultant',
    knowledge: 5,
    communication: 5,
    gsd: 5,
    innovation: 5,
    complexity: 4,
    ownership: 5,
    impact: 4,
    score: 37,
    level: 5
  },
  {
    department: 'Customer Solutions',
    title: 'Director of Customer Solutions',
    knowledge: 6,
    communication: 6,
    gsd: 6,
    innovation: 5,
    complexity: 5,
    ownership: 6,
    impact: 5,
    score: 44,
    level: 7
  },
  {
    department: 'Customer Success',
    title: 'Account Management Specialist',
    knowledge: 3,
    communication: 4,
    gsd: 3,
    innovation: 2,
    complexity: 3,
    ownership: 3,
    impact: 3,
    score: 24,
    level: 3
  },
  {
    department: 'Customer Success',
    title: 'Account Manager',
    knowledge: 4,
    communication: 5,
    gsd: 4,
    innovation: 3,
    complexity: 4,
    ownership: 4,
    impact: 3,
    score: 30,
    level: 4
  },
  {
    department: 'Customer Success',
    title: 'Sr. Account Management Manager',
    knowledge: 5,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 4,
    ownership: 5,
    impact: 4,
    score: 38,
    level: 6
  },
  {
    department: 'Customer Success',
    title: 'Customer Engagement Manager',
    knowledge: 4,
    communication: 5,
    gsd: 4,
    innovation: 4,
    complexity: 4,
    ownership: 4,
    impact: 4,
    score: 33,
    level: 4
  },
  {
    department: 'Customer Success',
    title: 'Sr. Customer Success Analyst',
    knowledge: 5,
    communication: 5,
    gsd: 5,
    innovation: 4,
    complexity: 4,
    ownership: 4,
    impact: 4,
    score: 35,
    level: 5
  },
  {
    department: 'Decision Science',
    title: 'Reporting Analyst',
    knowledge: 4,
    communication: 4,
    gsd: 4,
    innovation: 4,
    complexity: 4,
    ownership: 4,
    impact: 3,
    score: 30,
    level: 4
  },
  {
    department: 'Decision Science',
    title: 'Senior Reporting Analyst',
    knowledge: 5,
    communication: 5,
    gsd: 5,
    innovation: 4,
    complexity: 4,
    ownership: 5,
    impact: 4,
    score: 36,
    level: 5
  },
  {
    department: 'Decision Science',
    title: 'Lead Reporting Analyst',
    knowledge: 6,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 5,
    ownership: 5,
    impact: 5,
    score: 42,
    level: 6
  },
  {
    department: 'Decision Science',
    title: 'Lead Predictive Analyst',
    knowledge: 5,
    communication: 6,
    gsd: 5,
    innovation: 4,
    complexity: 5,
    ownership: 5,
    impact: 4,
    score: 38,
    level: 6
  },
  {
    department: 'Decision Science',
    title: 'Director Predictive Analytics',
    knowledge: 6,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 6,
    ownership: 5,
    impact: 5,
    score: 43,
    level: 7
  },
  {
    department: 'Decision Science',
    title: 'Analytics Director',
    knowledge: 6,
    communication: 6,
    gsd: 6,
    innovation: 5,
    complexity: 6,
    ownership: 6,
    impact: 5,
    score: 45,
    level: 7
  },
  {
    department: 'Decision Science',
    title: 'Lead Consumer Insights Researcher',
    knowledge: 5,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 4,
    ownership: 5,
    impact: 4,
    score: 38,
    level: 6
  },
  {
    department: 'Decision Science',
    title: 'Sr. Consumer Insights Researcher',
    knowledge: 5,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 4,
    ownership: 5,
    impact: 3,
    score: 36,
    level: 5
  },
  {
    department: 'Decision Science',
    title: 'Sr. Analytics Manager',
    knowledge: 6,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 5,
    ownership: 5,
    impact: 5,
    score: 42,
    level: 6
  },
  {
    department: 'Decision Science',
    title: 'Sr. Director, Data Science',
    knowledge: 6,
    communication: 7,
    gsd: 6,
    innovation: 6,
    complexity: 6,
    ownership: 6,
    impact: 5,
    score: 47,
    level: 8
  },
  {
    department: 'Engineering',
    title: 'Engineer',
    knowledge: 4,
    communication: 4,
    gsd: 3,
    innovation: 4,
    complexity: 4,
    ownership: 4,
    impact: 3,
    score: 29,
    level: 4
  },
  {
    department: 'Engineering',
    title: 'Data Scientist',
    knowledge: 4,
    communication: 4,
    gsd: 3,
    innovation: 5,
    complexity: 5,
    ownership: 4,
    impact: 3,
    score: 31,
    level: 4
  },
  {
    department: 'Engineering',
    title: 'Engineering Manager',
    knowledge: 4,
    communication: 6,
    gsd: 4,
    innovation: 4,
    complexity: 5,
    ownership: 5,
    impact: 3,
    score: 34,
    level: 5
  },
  {
    department: 'Engineering',
    title: 'Data Scientist Manager',
    knowledge: 4,
    communication: 6,
    gsd: 4,
    innovation: 5,
    complexity: 5,
    ownership: 5,
    impact: 3,
    score: 35,
    level: 5
  },
  {
    department: 'Engineering',
    title: 'Sr. Engineer',
    knowledge: 5,
    communication: 5,
    gsd: 4,
    innovation: 5,
    complexity: 5,
    ownership: 5,
    impact: 3,
    score: 35,
    level: 5
  },
  {
    department: 'Engineering',
    title: 'Sr. Data Scientist',
    knowledge: 5,
    communication: 5,
    gsd: 4,
    innovation: 5,
    complexity: 5,
    ownership: 5,
    impact: 3,
    score: 35,
    level: 5
  },
  {
    department: 'Engineering',
    title: 'Senior Engineering Manager',
    knowledge: 5,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 5,
    ownership: 5,
    impact: 4,
    score: 39,
    level: 6
  },
  {
    department: 'Engineering',
    title: 'Senior Data Scientist Manager',
    knowledge: 5,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 5,
    ownership: 5,
    impact: 4,
    score: 39,
    level: 6
  },
  {
    department: 'Engineering',
    title: 'Engineering Director',
    knowledge: 6,
    communication: 6,
    gsd: 6,
    innovation: 6,
    complexity: 6,
    ownership: 6,
    impact: 4,
    score: 44,
    level: 7
  },
  {
    department: 'Engineering',
    title: 'VP - Engineering',
    knowledge: 7,
    communication: 6,
    gsd: 6,
    innovation: 7,
    complexity: 6,
    ownership: 7,
    impact: 5,
    score: 49,
    level: 9
  },
  {
    department: 'Facilities',
    title: 'Front Office Coordinator',
    knowledge: 2,
    communication: 4,
    gsd: 2,
    innovation: 2,
    complexity: 3,
    ownership: 3,
    impact: 3,
    score: 22,
    level: 2
  },
  {
    department: 'Facilities',
    title: 'Sr. Facilities Specialist',
    knowledge: 3,
    communication: 4,
    gsd: 4,
    innovation: 4,
    complexity: 4,
    ownership: 4,
    impact: 4,
    score: 31,
    level: 4
  },
  {
    department: 'Facilities',
    title: 'Office Manager',
    knowledge: 4,
    communication: 5,
    gsd: 4,
    innovation: 4,
    complexity: 4,
    ownership: 4,
    impact: 4,
    score: 33,
    level: 4
  },
  {
    department: 'Facilities',
    title: 'Facilitites Supervisor',
    knowledge: 4,
    communication: 5,
    gsd: 4,
    innovation: 4,
    complexity: 4,
    ownership: 4,
    impact: 4,
    score: 33,
    level: 4
  },
  {
    department: 'Facilities',
    title: 'Facilities Manager',
    knowledge: 5,
    communication: 5,
    gsd: 5,
    innovation: 4,
    complexity: 5,
    ownership: 5,
    impact: 4,
    score: 37,
    level: 5
  },
  {
    department: 'Facilities',
    title: 'Sr. Facilities Design Manager',
    knowledge: 6,
    communication: 5,
    gsd: 5,
    innovation: 6,
    complexity: 6,
    ownership: 6,
    impact: 4,
    score: 42,
    level: 6
  },
  {
    department: 'Facilities',
    title: 'Sr. Facilities Designer',
    knowledge: 5,
    communication: 5,
    gsd: 4,
    innovation: 5,
    complexity: 5,
    ownership: 5,
    impact: 4,
    score: 37,
    level: 5
  },
  {
    department: 'Facilities',
    title: 'Sr. Construction Manager',
    knowledge: 5,
    communication: 5,
    gsd: 5,
    innovation: 4,
    complexity: 5,
    ownership: 5,
    impact: 4,
    score: 37,
    level: 5
  },
  {
    department: 'Finance',
    title: 'Financial Planner & Analyst',
    knowledge: 4,
    communication: 4,
    gsd: 4,
    innovation: 3,
    complexity: 3,
    ownership: 4,
    impact: 4,
    score: 30,
    level: 4
  },
  {
    department: 'Finance',
    title: 'Director, FP&A',
    knowledge: 6,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 6,
    ownership: 5,
    impact: 5,
    score: 43,
    level: 7
  },
  {
    department: 'Finance',
    title: 'Tax Director',
    knowledge: 6,
    communication: 6,
    gsd: 5,
    innovation: 7,
    complexity: 6,
    ownership: 5,
    impact: 5,
    score: 45,
    level: 7
  },
  {
    department: 'Finance',
    title: 'Directory of Treasury',
    knowledge: 6,
    communication: 5,
    gsd: 5,
    innovation: 5,
    complexity: 5,
    ownership: 6,
    impact: 4,
    score: 40,
    level: 6
  },
  {
    department: 'Finance',
    title: 'Senior Tax Accountant',
    knowledge: 5,
    communication: 5,
    gsd: 4,
    innovation: 5,
    complexity: 5,
    ownership: 5,
    impact: 4,
    score: 37,
    level: 5
  },
  {
    department: 'Finance',
    title: 'Sr. Financial Planner & Analyst',
    knowledge: 5,
    communication: 5,
    gsd: 4,
    innovation: 5,
    complexity: 5,
    ownership: 5,
    impact: 4,
    score: 37,
    level: 5
  },
  {
    department: 'Finance',
    title: 'Sr. Accounting Specialist',
    knowledge: 4,
    communication: 4,
    gsd: 4,
    innovation: 3,
    complexity: 3,
    ownership: 3,
    impact: 3,
    score: 27,
    level: 3
  },
  {
    department: 'Finance',
    title: 'Sr. Accountant',
    knowledge: 5,
    communication: 6,
    gsd: 4,
    innovation: 4,
    complexity: 5,
    ownership: 5,
    impact: 4,
    score: 37,
    level: 5
  },
  {
    department: 'Finance',
    title: 'Regional Controller',
    knowledge: 6,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 6,
    ownership: 6,
    impact: 4,
    score: 42,
    level: 6
  },
  {
    department: 'Finance',
    title: 'Sr. Manager, Accounting',
    knowledge: 5,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 5,
    ownership: 6,
    impact: 4,
    score: 40,
    level: 6
  },
  {
    department: 'Finance',
    title: 'Accountant',
    knowledge: 4,
    communication: 4,
    gsd: 4,
    innovation: 4,
    complexity: 3,
    ownership: 4,
    impact: 3,
    score: 29,
    level: 4
  },
  {
    department: 'Finance',
    title: 'Accounting Specialist',
    knowledge: 4,
    communication: 4,
    gsd: 3,
    innovation: 3,
    complexity: 3,
    ownership: 3,
    impact: 3,
    score: 26,
    level: 3
  },
  {
    department: 'Finance',
    title: 'Accounts Payable Supervisor',
    knowledge: 4,
    communication: 4,
    gsd: 4,
    innovation: 3,
    complexity: 4,
    ownership: 4,
    impact: 3,
    score: 29,
    level: 4
  },
  {
    department: 'Finance',
    title: 'Accounts Payable Specialist',
    knowledge: 3,
    communication: 4,
    gsd: 3,
    innovation: 2,
    complexity: 3,
    ownership: 3,
    impact: 3,
    score: 24,
    level: 3
  },
  {
    department: 'Finance',
    title: 'Billing Specialist',
    knowledge: 3,
    communication: 4,
    gsd: 3,
    innovation: 3,
    complexity: 3,
    ownership: 4,
    impact: 3,
    score: 26,
    level: 3
  },
  {
    department: 'Finance',
    title: 'VP, Accounting',
    knowledge: 7,
    communication: 6,
    gsd: 7,
    innovation: 5,
    complexity: 7,
    ownership: 6,
    impact: 6,
    score: 50,
    level: 9
  },
  {
    department: 'Hardware',
    title: 'Sr. Hardware Operations Manager',
    knowledge: 6,
    communication: 6,
    gsd: 5,
    innovation: 6,
    complexity: 5,
    ownership: 6,
    impact: 4,
    score: 42,
    level: 6
  },
  {
    department: 'Hardware',
    title: 'Camera Hardware Lead',
    knowledge: 6,
    communication: 5,
    gsd: 6,
    innovation: 5,
    complexity: 5,
    ownership: 6,
    impact: 4,
    score: 41,
    level: 6
  },
  {
    department: 'Hardware',
    title: 'Supply Chain Coordinator',
    knowledge: 4,
    communication: 4,
    gsd: 3,
    innovation: 3,
    complexity: 4,
    ownership: 4,
    impact: 3,
    score: 28,
    level: 3
  },
  {
    department: 'Hardware',
    title: 'Operations Project Manager',
    knowledge: 4,
    communication: 5,
    gsd: 4,
    innovation: 4,
    complexity: 4,
    ownership: 4,
    impact: 3,
    score: 31,
    level: 4
  },
  {
    department: 'Hardware',
    title: 'VP - Hardware',
    knowledge: 6,
    communication: 7,
    gsd: 6,
    innovation: 6,
    complexity: 7,
    ownership: 7,
    impact: 5,
    score: 49,
    level: 9
  },
  {
    department: 'IT',
    title: 'Workstation Administrator',
    knowledge: 4,
    communication: 4,
    gsd: 4,
    innovation: 3,
    complexity: 4,
    ownership: 4,
    impact: 3,
    score: 29,
    level: 4
  },
  {
    department: 'IT',
    title: 'Sr. Workstation Administrator',
    knowledge: 5,
    communication: 4,
    gsd: 5,
    innovation: 4,
    complexity: 4,
    ownership: 5,
    impact: 4,
    score: 35,
    level: 5
  },
  {
    department: 'IT',
    title: 'Lead Network Administrator',
    knowledge: 6,
    communication: 4,
    gsd: 5,
    innovation: 5,
    complexity: 5,
    ownership: 6,
    impact: 4,
    score: 39,
    level: 6
  },
  {
    department: 'IT',
    title: 'IT Director',
    knowledge: 6,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 6,
    ownership: 6,
    impact: 6,
    score: 46,
    level: 7
  },
  {
    department: 'Legal',
    title: 'EVP of Legal',
    knowledge: 7,
    communication: 8,
    gsd: 7,
    innovation: 6,
    complexity: 6,
    ownership: 6,
    impact: 7,
    score: 54,
    level: 10
  },
  {
    department: 'Legal',
    title: 'Deputy General Counsel',
    knowledge: 6,
    communication: 7,
    gsd: 6,
    innovation: 5,
    complexity: 6,
    ownership: 6,
    impact: 5,
    score: 46,
    level: 7
  },
  {
    department: 'Legal',
    title: 'Lead Legal Counsel',
    knowledge: 5,
    communication: 5,
    gsd: 5,
    innovation: 5,
    complexity: 6,
    ownership: 4,
    impact: 4,
    score: 38,
    level: 6
  },
  {
    department: 'Legal',
    title: 'Associate Counsel',
    knowledge: 5,
    communication: 4,
    gsd: 4,
    innovation: 4,
    complexity: 4,
    ownership: 4,
    impact: 4,
    score: 33,
    level: 4
  },
  {
    department: 'Marketing - Brand',
    title: 'Video Content Producer',
    knowledge: 4,
    communication: 5,
    gsd: 4,
    innovation: 3,
    complexity: 4,
    ownership: 3,
    impact: 4,
    score: 31,
    level: 4
  },
  {
    department: 'Marketing - Brand',
    title: 'Content Producer',
    knowledge: 4,
    communication: 5,
    gsd: 4,
    innovation: 3,
    complexity: 4,
    ownership: 3,
    impact: 4,
    score: 31,
    level: 4
  },
  {
    department: 'Marketing - Brand',
    title: 'Brand Designer',
    knowledge: 4,
    communication: 4,
    gsd: 4,
    innovation: 4,
    complexity: 4,
    ownership: 3,
    impact: 4,
    score: 31,
    level: 4
  },
  {
    department: 'Marketing - Operations',
    title: 'Sr. Specialist, Marketing Technology',
    knowledge: 4,
    communication: 4,
    gsd: 4,
    innovation: 4,
    complexity: 4,
    ownership: 4,
    impact: 4,
    score: 32,
    level: 4
  },
  {
    department: 'Marketing Ops',
    title: 'Sr. Specialist, Partnerships and Events',
    knowledge: 4,
    communication: 5,
    gsd: 4,
    innovation: 4,
    complexity: 4,
    ownership: 4,
    impact: 4,
    score: 33,
    level: 4
  },
  {
    department: 'Marketing - Brand',
    title: 'Manager, Content Marketing',
    knowledge: 5,
    communication: 6,
    gsd: 4,
    innovation: 5,
    complexity: 4,
    ownership: 5,
    impact: 4,
    score: 37,
    level: 5
  },
  {
    department: 'Marketing Ops',
    title: 'Manager, Partnership and Events',
    knowledge: 5,
    communication: 5,
    gsd: 4,
    innovation: 5,
    complexity: 5,
    ownership: 5,
    impact: 4,
    score: 37,
    level: 5
  },
  {
    department: 'Marketing Ops',
    title: 'Manager, Project Management',
    knowledge: 5,
    communication: 6,
    gsd: 4,
    innovation: 5,
    complexity: 4,
    ownership: 5,
    impact: 4,
    score: 37,
    level: 5
  },
  {
    department: 'Marketing - Brand',
    title: 'Sr. Content Producer',
    knowledge: 5,
    communication: 4,
    gsd: 4,
    innovation: 6,
    complexity: 5,
    ownership: 5,
    impact: 4,
    score: 37,
    level: 5
  },
  {
    department: 'Marketing Ops',
    title: 'Sr. Marketing Manager',
    knowledge: 5,
    communication: 5,
    gsd: 5,
    innovation: 4,
    complexity: 5,
    ownership: 5,
    impact: 4,
    score: 37,
    level: 5
  },
  {
    department: 'Marketing - Brand',
    title: 'Sr. Front End Developer',
    knowledge: 5,
    communication: 4,
    gsd: 5,
    innovation: 5,
    complexity: 5,
    ownership: 4,
    impact: 4,
    score: 36,
    level: 5
  },
  {
    department: 'Marketing Ops',
    title: 'Sr. Program Manager',
    knowledge: 5,
    communication: 6,
    gsd: 5,
    innovation: 4,
    complexity: 4,
    ownership: 5,
    impact: 4,
    score: 37,
    level: 5
  },
  {
    department: 'Marketing - Brand',
    title: 'Sr. Web Developer',
    knowledge: 5,
    communication: 6,
    gsd: 4,
    innovation: 5,
    complexity: 4,
    ownership: 5,
    impact: 4,
    score: 37,
    level: 5
  },
  {
    department: 'Marketing - Operations',
    title: 'Sr. Digital Marketing Manager',
    knowledge: 5,
    communication: 5,
    gsd: 4,
    innovation: 5,
    complexity: 5,
    ownership: 5,
    impact: 4,
    score: 37,
    level: 5
  },
  {
    department: 'Marketing - Brand',
    title: 'Lead Web Developer',
    knowledge: 6,
    communication: 5,
    gsd: 5,
    innovation: 6,
    complexity: 6,
    ownership: 6,
    impact: 4,
    score: 42,
    level: 6
  },
  {
    department: 'Marketing - Brand',
    title: 'Sr. Manager, Marketing Design',
    knowledge: 6,
    communication: 5,
    gsd: 4,
    innovation: 4,
    complexity: 4,
    ownership: 5,
    impact: 5,
    score: 38,
    level: 6
  },
  {
    department: 'Marketing - Brand',
    title: 'Lead Brand Marketing Manager',
    knowledge: 6,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 5,
    ownership: 6,
    impact: 4,
    score: 41,
    level: 6
  },
  {
    department: 'Marketing Ops',
    title: 'Sr. Manager, Marketing Operations',
    knowledge: 6,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 5,
    ownership: 6,
    impact: 4,
    score: 41,
    level: 6
  },
  {
    department: 'Marketing Ops',
    title: 'Marketing Automation Manager',
    knowledge: 6,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 5,
    ownership: 6,
    impact: 4,
    score: 41,
    level: 6
  },
  {
    department: 'Marketing - Brand',
    title: 'Sr. Manager, Content Marketing',
    knowledge: 5,
    communication: 5,
    gsd: 4,
    innovation: 5,
    complexity: 5,
    ownership: 5,
    impact: 5,
    score: 39,
    level: 6
  },
  {
    department: 'Business Operations',
    title: 'VP - Market (Elite/Competitive)',
    knowledge: 6,
    communication: 8,
    gsd: 6,
    innovation: 7,
    complexity: 7,
    ownership: 6,
    impact: 5,
    score: 50,
    level: 9
  },
  {
    department: 'Marketing Ops',
    title: 'VP Marketing',
    knowledge: 6,
    communication: 7,
    gsd: 7,
    innovation: 6,
    complexity: 6,
    ownership: 7,
    impact: 5,
    score: 49,
    level: 9
  },
  {
    department: 'Media',
    title: 'Sr. Programming Manager',
    knowledge: 5,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 6,
    ownership: 5,
    impact: 4,
    score: 40,
    level: 6
  },
  {
    department: 'Media',
    title: 'Sr. Brand Account Partner',
    knowledge: 5,
    communication: 5,
    gsd: 4,
    innovation: 4,
    complexity: 5,
    ownership: 5,
    impact: 3,
    score: 34,
    level: 5
  },
  {
    department: 'Media',
    title: 'Sr. Video Production Manager',
    knowledge: 5,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 5,
    ownership: 6,
    impact: 4,
    score: 40,
    level: 6
  },
  {
    department: 'Media',
    title: 'Media Operations Mgr',
    knowledge: 4,
    communication: 5,
    gsd: 5,
    innovation: 5,
    complexity: 5,
    ownership: 4,
    impact: 3,
    score: 34,
    level: 5
  },
  {
    department: 'Media',
    title: 'Lead Media Services Partner',
    knowledge: 5,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 5,
    ownership: 6,
    impact: 4,
    score: 40,
    level: 6
  },
  {
    department: 'Media',
    title: 'Sr. Media Operations Specialist',
    knowledge: 5,
    communication: 4,
    gsd: 4,
    innovation: 4,
    complexity: 5,
    ownership: 4,
    impact: 3,
    score: 32,
    level: 4
  },
  {
    department: 'Media',
    title: 'Sr. Video Production Specialist',
    knowledge: 4,
    communication: 4,
    gsd: 4,
    innovation: 4,
    complexity: 4,
    ownership: 3,
    impact: 3,
    score: 29,
    level: 4
  },
  {
    department: 'Media',
    title: 'Sr. Video Producer',
    knowledge: 5,
    communication: 5,
    gsd: 5,
    innovation: 4,
    complexity: 4,
    ownership: 4,
    impact: 4,
    score: 35,
    level: 5
  },
  {
    department: 'Media',
    title: 'Sr. Social Media Specialist',
    knowledge: 4,
    communication: 5,
    gsd: 4,
    innovation: 4,
    complexity: 3,
    ownership: 3,
    impact: 3,
    score: 29,
    level: 4
  },
  {
    department: 'Operations',
    title: 'VP - Assist Operations',
    knowledge: 6,
    communication: 7,
    gsd: 7,
    innovation: 6,
    complexity: 6,
    ownership: 6,
    impact: 6,
    score: 50,
    level: 9
  },
  {
    department: 'Operations',
    title: 'Assist Operations Specialist',
    knowledge: 3,
    communication: 4,
    gsd: 3,
    innovation: 3,
    complexity: 3,
    ownership: 3,
    impact: 3,
    score: 25,
    level: 3
  },
  {
    department: 'Operations',
    title: 'Operations Analyst',
    knowledge: 3,
    communication: 4,
    gsd: 4,
    innovation: 4,
    complexity: 4,
    ownership: 4,
    impact: 4,
    score: 31,
    level: 4
  },
  {
    department: 'Operations',
    title: 'Assist Trainer',
    knowledge: 3,
    communication: 6,
    gsd: 4,
    innovation: 3,
    complexity: 3,
    ownership: 4,
    impact: 3,
    score: 29,
    level: 4
  },
  {
    department: 'Operations',
    title: 'Sr. Site Manager',
    knowledge: 5,
    communication: 6,
    gsd: 5,
    innovation: 4,
    complexity: 5,
    ownership: 5,
    impact: 4,
    score: 38,
    level: 6
  },
  {
    department: 'Operations',
    title: 'Operations Project Manager',
    knowledge: 3,
    communication: 6,
    gsd: 4,
    innovation: 5,
    complexity: 5,
    ownership: 5,
    impact: 4,
    score: 36,
    level: 5
  },
  {
    department: 'Operations',
    title: 'Production Manager',
    knowledge: 4,
    communication: 5,
    gsd: 4,
    innovation: 3,
    complexity: 4,
    ownership: 4,
    impact: 4,
    score: 32,
    level: 4
  },
  {
    department: 'Operations',
    title: 'Lead Systems Analyst',
    knowledge: 4,
    communication: 5,
    gsd: 5,
    innovation: 6,
    complexity: 7,
    ownership: 5,
    impact: 4,
    score: 40,
    level: 6
  },
  {
    department: 'Operations',
    title: 'VP - Operations',
    knowledge: 6,
    communication: 7,
    gsd: 7,
    innovation: 6,
    complexity: 6,
    ownership: 6,
    impact: 6,
    score: 50,
    level: 9
  },
  {
    department: 'People Ops',
    title: 'Talent Acquisition Director',
    knowledge: 6,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 5,
    ownership: 6,
    impact: 5,
    score: 43,
    level: 7
  },
  {
    department: 'People Ops',
    title: 'Learning & Development Director',
    knowledge: 6,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 5,
    ownership: 6,
    impact: 5,
    score: 43,
    level: 7
  },
  {
    department: 'People Ops',
    title: 'Talent & Culture Director',
    knowledge: 6,
    communication: 6,
    gsd: 5,
    innovation: 6,
    complexity: 5,
    ownership: 6,
    impact: 5,
    score: 44,
    level: 7
  },
  {
    department: 'People Ops',
    title: 'Lead Recruiter',
    knowledge: 5,
    communication: 5,
    gsd: 5,
    innovation: 4,
    complexity: 5,
    ownership: 6,
    impact: 4,
    score: 38,
    level: 6
  },
  {
    department: 'People Ops',
    title: 'Sr. Recruiter',
    knowledge: 4,
    communication: 5,
    gsd: 4,
    innovation: 4,
    complexity: 4,
    ownership: 5,
    impact: 4,
    score: 34,
    level: 5
  },
  {
    department: 'People Ops',
    title: 'Recruiter',
    knowledge: 4,
    communication: 5,
    gsd: 4,
    innovation: 3,
    complexity: 3,
    ownership: 4,
    impact: 3,
    score: 29,
    level: 4
  },
  {
    department: 'People Ops',
    title: 'Sr. Talent Acquisition Specialist',
    knowledge: 4,
    communication: 5,
    gsd: 4,
    innovation: 3,
    complexity: 3,
    ownership: 4,
    impact: 3,
    score: 29,
    level: 4
  },
  {
    department: 'People Ops',
    title: 'Lead HR Business Partner',
    knowledge: 5,
    communication: 5,
    gsd: 5,
    innovation: 4,
    complexity: 5,
    ownership: 6,
    impact: 4,
    score: 38,
    level: 6
  },
  {
    department: 'People Ops',
    title: 'Sr. HR Business Partner',
    knowledge: 5,
    communication: 5,
    gsd: 4,
    innovation: 4,
    complexity: 4,
    ownership: 5,
    impact: 4,
    score: 35,
    level: 5
  },
  {
    department: 'People Ops',
    title: 'HR Business Partner',
    knowledge: 4,
    communication: 5,
    gsd: 4,
    innovation: 3,
    complexity: 3,
    ownership: 4,
    impact: 3,
    score: 29,
    level: 4
  },
  {
    department: 'People Ops',
    title: 'Sr. Business Partner - L&D',
    knowledge: 5,
    communication: 5,
    gsd: 4,
    innovation: 4,
    complexity: 5,
    ownership: 5,
    impact: 3,
    score: 34,
    level: 5
  },
  {
    department: 'People Ops',
    title: 'Business Partner - L&D',
    knowledge: 5,
    communication: 5,
    gsd: 4,
    innovation: 3,
    complexity: 4,
    ownership: 4,
    impact: 3,
    score: 31,
    level: 4
  },
  {
    department: 'People Ops',
    title: 'L&D Coordinator',
    knowledge: 4,
    communication: 4,
    gsd: 3,
    innovation: 3,
    complexity: 3,
    ownership: 3,
    impact: 3,
    score: 26,
    level: 3
  },
  {
    department: 'People Ops',
    title: 'Sr. HR Specialist',
    knowledge: 4,
    communication: 4,
    gsd: 4,
    innovation: 3,
    complexity: 4,
    ownership: 5,
    impact: 3,
    score: 30,
    level: 4
  },
  {
    department: 'People Ops',
    title: 'HR Specialist',
    knowledge: 4,
    communication: 4,
    gsd: 3,
    innovation: 3,
    complexity: 3,
    ownership: 3,
    impact: 3,
    score: 26,
    level: 3
  },
  {
    department: 'People Ops',
    title: 'People Ops Dir',
    knowledge: 7,
    communication: 7,
    gsd: 7,
    innovation: 7,
    complexity: 6,
    ownership: 6,
    impact: 7,
    score: 54,
    level: 10
  },
  {
    department: 'Product',
    title: 'Sr Product Director (Tribe Lead)',
    knowledge: 6,
    communication: 7,
    gsd: 6,
    innovation: 6,
    complexity: 6,
    ownership: 6,
    impact: 5,
    score: 47,
    level: 8
  },
  {
    department: 'Product Design',
    title: 'Product Designer',
    knowledge: 5,
    communication: 4,
    gsd: 4,
    innovation: 3,
    complexity: 4,
    ownership: 4,
    impact: 3,
    score: 30,
    level: 4
  },
  {
    department: 'Product Design',
    title: 'Senior Product Designer',
    knowledge: 5,
    communication: 5,
    gsd: 4,
    innovation: 4,
    complexity: 5,
    ownership: 5,
    impact: 4,
    score: 36,
    level: 5
  },
  {
    department: 'Product Design',
    title: 'Lead Designer',
    knowledge: 6,
    communication: 6,
    gsd: 4,
    innovation: 5,
    complexity: 5,
    ownership: 5,
    impact: 4,
    score: 39,
    level: 6
  },
  {
    department: 'Product Design',
    title: 'Principal Designer',
    knowledge: 6,
    communication: 6,
    gsd: 5,
    innovation: 6,
    complexity: 6,
    ownership: 6,
    impact: 4,
    score: 43,
    level: 7
  },
  {
    department: 'Product Design',
    title: 'Design Manager',
    knowledge: 5,
    communication: 5,
    gsd: 5,
    innovation: 4,
    complexity: 4,
    ownership: 5,
    impact: 3,
    score: 34,
    level: 5
  },
  {
    department: 'Product Design',
    title: 'Design Director',
    knowledge: 6,
    communication: 6,
    gsd: 6,
    innovation: 6,
    complexity: 5,
    ownership: 6,
    impact: 4,
    score: 43,
    level: 7
  },
  {
    department: 'Product Design',
    title: 'VP - Design',
    knowledge: 7,
    communication: 7,
    gsd: 6,
    innovation: 7,
    complexity: 6,
    ownership: 7,
    impact: 5,
    score: 50,
    level: 9
  },
  {
    department: 'Product Design',
    title: 'Industrial Designer',
    knowledge: 4,
    communication: 4,
    gsd: 4,
    innovation: 4,
    complexity: 4,
    ownership: 5,
    impact: 4,
    score: 33,
    level: 4
  },
  {
    department: 'Product Design',
    title: 'Assoc. Ind. Designer',
    knowledge: 4,
    communication: 3,
    gsd: 3,
    innovation: 3,
    complexity: 4,
    ownership: 3,
    impact: 3,
    score: 26,
    level: 3
  },
  {
    department: 'Product Design',
    title: 'Sr. Info Architect',
    knowledge: 5,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 5,
    ownership: 6,
    impact: 4,
    score: 40,
    level: 6
  },
  {
    department: 'Product Design',
    title: 'Product UX Writer',
    knowledge: 4,
    communication: 5,
    gsd: 4,
    innovation: 3,
    complexity: 4,
    ownership: 5,
    impact: 4,
    score: 33,
    level: 4
  },
  {
    department: 'Product Managers',
    title: 'Product Manager',
    knowledge: 4,
    communication: 4,
    gsd: 5,
    innovation: 4,
    complexity: 3,
    ownership: 4,
    impact: 3,
    score: 30,
    level: 4
  },
  {
    department: 'Product Managers',
    title: 'Sr. Product Manager',
    knowledge: 5,
    communication: 5,
    gsd: 5,
    innovation: 5,
    complexity: 4,
    ownership: 5,
    impact: 3,
    score: 35,
    level: 5
  },
  {
    department: 'Product Managers',
    title: 'Sr. PM Manager',
    knowledge: 6,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 5,
    ownership: 6,
    impact: 4,
    score: 41,
    level: 6
  },
  {
    department: 'Product Managers',
    title: 'PM Director',
    knowledge: 6,
    communication: 6,
    gsd: 5,
    innovation: 6,
    complexity: 6,
    ownership: 6,
    impact: 4,
    score: 43,
    level: 7
  },
  {
    department: 'Product Managers',
    title: 'Distinguished Product Manager',
    knowledge: 6,
    communication: 6,
    gsd: 6,
    innovation: 6,
    complexity: 6,
    ownership: 7,
    impact: 5,
    score: 47,
    level: 8
  },
  {
    department: 'Product Managers',
    title: 'Sr. Product Director',
    knowledge: 6,
    communication: 6,
    gsd: 6,
    innovation: 6,
    complexity: 6,
    ownership: 7,
    impact: 5,
    score: 47,
    level: 8
  },
  {
    department: 'Product Managers',
    title: 'VP Product',
    knowledge: 7,
    communication: 6,
    gsd: 6,
    innovation: 7,
    complexity: 6,
    ownership: 7,
    impact: 5,
    score: 49,
    level: 9
  },
  {
    department: 'QA',
    title: 'Quality Analyst',
    knowledge: 4,
    communication: 4,
    gsd: 4,
    innovation: 3,
    complexity: 4,
    ownership: 4,
    impact: 3,
    score: 29,
    level: 4
  },
  {
    department: 'QA',
    title: 'Senior QA',
    knowledge: 5,
    communication: 5,
    gsd: 5,
    innovation: 4,
    complexity: 4,
    ownership: 5,
    impact: 4,
    score: 36,
    level: 5
  },
  {
    department: 'QA',
    title: 'Lead QA',
    knowledge: 5,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 5,
    ownership: 5,
    impact: 4,
    score: 39,
    level: 6
  },
  {
    department: 'QA',
    title: 'QA Manager',
    knowledge: 5,
    communication: 5,
    gsd: 5,
    innovation: 5,
    complexity: 5,
    ownership: 4,
    impact: 4,
    score: 37,
    level: 5
  },
  {
    department: 'QA',
    title: 'QA Director',
    knowledge: 6,
    communication: 6,
    gsd: 6,
    innovation: 6,
    complexity: 5,
    ownership: 6,
    impact: 5,
    score: 45,
    level: 7
  },
  {
    department: 'QA',
    title: 'VP - Quality',
    knowledge: 7,
    communication: 7,
    gsd: 7,
    innovation: 6,
    complexity: 6,
    ownership: 7,
    impact: 5,
    score: 50,
    level: 9
  },
  {
    department: 'Sales',
    title: 'Regional Director (International Only)',
    knowledge: 6,
    communication: 6,
    gsd: 6,
    innovation: 4,
    complexity: 5,
    ownership: 5,
    impact: 4,
    score: 40,
    level: 6
  },
  {
    department: 'Sales',
    title: 'Sales Manager',
    knowledge: 4,
    communication: 6,
    gsd: 4,
    innovation: 4,
    complexity: 5,
    ownership: 4,
    impact: 4,
    score: 35,
    level: 5
  },
  {
    department: 'Sales',
    title: 'Inside Sales Specialist',
    knowledge: 3,
    communication: 4,
    gsd: 3,
    innovation: 3,
    complexity: 3,
    ownership: 3,
    impact: 3,
    score: 25,
    level: 3
  },
  {
    department: 'Sales',
    title: 'Account Executive',
    knowledge: 4,
    communication: 5,
    gsd: 4,
    innovation: 3,
    complexity: 3,
    ownership: 4,
    impact: 3,
    score: 29,
    level: 4
  },
  {
    department: 'Sales',
    title: 'Elite Account Executive',
    knowledge: 4,
    communication: 5,
    gsd: 4,
    innovation: 3,
    complexity: 3,
    ownership: 4,
    impact: 3,
    score: 29,
    level: 4
  },
  {
    department: 'Sales',
    title: 'Sr. Elite Account Executive',
    knowledge: 5,
    communication: 6,
    gsd: 4,
    innovation: 4,
    complexity: 4,
    ownership: 3,
    impact: 4,
    score: 34,
    level: 5
  },
  {
    department: 'Sales',
    title: 'Territory Manager (International Only)',
    knowledge: 5,
    communication: 6,
    gsd: 4,
    innovation: 4,
    complexity: 4,
    ownership: 3,
    impact: 4,
    score: 34,
    level: 5
  },
  {
    department: 'Sales',
    title: 'Sr. Director, Sales',
    knowledge: 6,
    communication: 7,
    gsd: 6,
    innovation: 5,
    complexity: 6,
    ownership: 5,
    impact: 6,
    score: 47,
    level: 8
  },
  {
    department: 'Sales',
    title: 'EVP - Global Sales',
    knowledge: 7,
    communication: 8,
    gsd: 7,
    innovation: 6,
    complexity: 7,
    ownership: 7,
    impact: 6,
    score: 54,
    level: 10
  },
  {
    department: 'Sales',
    title: 'VP - Customer Success',
    knowledge: 7,
    communication: 7,
    gsd: 6,
    innovation: 6,
    complexity: 6,
    ownership: 6,
    impact: 6,
    score: 50,
    level: 9
  },
  {
    department: 'Sales Ops',
    title: 'Sales Ops Specialist',
    knowledge: 3,
    communication: 4,
    gsd: 3,
    innovation: 2,
    complexity: 3,
    ownership: 3,
    impact: 3,
    score: 24,
    level: 3
  },
  {
    department: 'Sales Ops',
    title: 'Sales Enablement Specialist',
    knowledge: 3,
    communication: 4,
    gsd: 3,
    innovation: 2,
    complexity: 3,
    ownership: 3,
    impact: 3,
    score: 24,
    level: 3
  },
  {
    department: 'Sales Ops',
    title: 'Sr. Specialist, Sales Enablement',
    knowledge: 4,
    communication: 5,
    gsd: 4,
    innovation: 4,
    complexity: 4,
    ownership: 4,
    impact: 3,
    score: 31,
    level: 4
  },
  {
    department: 'Sales Ops',
    title: 'Sales Enablement Manager',
    knowledge: 5,
    communication: 5,
    gsd: 4,
    innovation: 5,
    complexity: 4,
    ownership: 5,
    impact: 3,
    score: 34,
    level: 5
  },
  {
    department: 'Sales Ops',
    title: 'Sr. Sales Enablement Manager',
    knowledge: 6,
    communication: 6,
    gsd: 5,
    innovation: 6,
    complexity: 5,
    ownership: 6,
    impact: 4,
    score: 42,
    level: 6
  },
  {
    department: 'Sales Ops',
    title: 'Sr. Sales Systems Administrator',
    knowledge: 5,
    communication: 5,
    gsd: 5,
    innovation: 5,
    complexity: 5,
    ownership: 5,
    impact: 3,
    score: 36,
    level: 5
  },
  {
    department: 'Sales Ops',
    title: 'Sales Operations Analyst',
    knowledge: 5,
    communication: 4,
    gsd: 5,
    innovation: 4,
    complexity: 4,
    ownership: 4,
    impact: 3,
    score: 32,
    level: 4
  },
  {
    department: 'Sales Ops',
    title: 'Sales Operations Manager',
    knowledge: 5,
    communication: 5,
    gsd: 5,
    innovation: 4,
    complexity: 4,
    ownership: 5,
    impact: 3,
    score: 34,
    level: 5
  },
  {
    department: 'Sales Ops',
    title: 'Sales Operations Director',
    knowledge: 6,
    communication: 7,
    gsd: 5,
    innovation: 6,
    complexity: 6,
    ownership: 6,
    impact: 5,
    score: 46,
    level: 7
  },
  {
    department: 'ScrumMasters',
    title: 'ScrumMaster',
    knowledge: 4,
    communication: 5,
    gsd: 4,
    innovation: 3,
    complexity: 3,
    ownership: 4,
    impact: 3,
    score: 29,
    level: 4
  },
  {
    department: 'ScrumMasters',
    title: 'Sr. ScrumMaster',
    knowledge: 5,
    communication: 6,
    gsd: 5,
    innovation: 3,
    complexity: 4,
    ownership: 5,
    impact: 3,
    score: 34,
    level: 5
  },
  {
    department: 'ScrumMasters',
    title: 'Lead ScrumMaster',
    knowledge: 6,
    communication: 6,
    gsd: 5,
    innovation: 4,
    complexity: 5,
    ownership: 5,
    impact: 4,
    score: 39,
    level: 6
  },
  {
    department: 'ScrumMasters',
    title: 'Principal ScrumMaster',
    knowledge: 7,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 6,
    ownership: 6,
    impact: 5,
    score: 45,
    level: 7
  },
  {
    department: 'ScrumMasters',
    title: 'Sr. Delivery Manager',
    knowledge: 5,
    communication: 5,
    gsd: 5,
    innovation: 4,
    complexity: 5,
    ownership: 5,
    impact: 6,
    score: 41,
    level: 6
  },
  {
    department: 'ScrumMasters',
    title: 'Delivery Director',
    knowledge: 6,
    communication: 6,
    gsd: 6,
    innovation: 5,
    complexity: 6,
    ownership: 5,
    impact: 6,
    score: 46,
    level: 7
  },
  {
    department: 'ScrumMasters',
    title: 'Lead Agile Coach',
    knowledge: 6,
    communication: 6,
    gsd: 4,
    innovation: 4,
    complexity: 4,
    ownership: 5,
    impact: 6,
    score: 41,
    level: 6
  },
  {
    department: 'ScrumMasters',
    title: 'Director, Agile Coaching',
    knowledge: 6,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 5,
    ownership: 6,
    impact: 6,
    score: 45,
    level: 7
  },
  {
    department: 'ScrumMasters',
    title: 'Sr. Director, Agile Coaching',
    knowledge: 6,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 6,
    ownership: 7,
    impact: 6,
    score: 47,
    level: 8
  },
  {
    department: 'Support',
    title: 'Support Experience Analyst',
    knowledge: 4,
    communication: 4,
    gsd: 4,
    innovation: 4,
    complexity: 4,
    ownership: 4,
    impact: 3,
    score: 30,
    level: 4
  },
  {
    department: 'Support',
    title: 'Support Experience Manager',
    knowledge: 5,
    communication: 5,
    gsd: 5,
    innovation: 5,
    complexity: 5,
    ownership: 4,
    impact: 4,
    score: 37,
    level: 5
  },
  {
    department: 'Support',
    title: 'Support Specialist',
    knowledge: 3,
    communication: 4,
    gsd: 4,
    innovation: 3,
    complexity: 3,
    ownership: 3,
    impact: 3,
    score: 26,
    level: 3
  },
  {
    department: 'Support',
    title: 'Support Manager',
    knowledge: 4,
    communication: 6,
    gsd: 4,
    innovation: 4,
    complexity: 4,
    ownership: 5,
    impact: 4,
    score: 35,
    level: 5
  },
  {
    department: 'Support',
    title: 'Support Technical Analyst',
    knowledge: 3,
    communication: 5,
    gsd: 3,
    innovation: 3,
    complexity: 4,
    ownership: 4,
    impact: 4,
    score: 30,
    level: 4
  },
  {
    department: 'Support',
    title: 'Sr. Support Engineer',
    knowledge: 5,
    communication: 4,
    gsd: 5,
    innovation: 5,
    complexity: 4,
    ownership: 5,
    impact: 4,
    score: 36,
    level: 5
  },
  {
    department: 'Support',
    title: 'Director of Elite Support',
    knowledge: 6,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 5,
    ownership: 6,
    impact: 5,
    score: 43,
    level: 7
  },
  {
    department: 'Support',
    title: 'Senior Manager, Support',
    knowledge: 5,
    communication: 6,
    gsd: 5,
    innovation: 5,
    complexity: 4,
    ownership: 6,
    impact: 4,
    score: 39,
    level: 6
  },
  {
    department: 'Support',
    title: 'Support Rotational Partner',
    knowledge: 3,
    communication: 4,
    gsd: 4,
    innovation: 4,
    complexity: 4,
    ownership: 4,
    impact: 3,
    score: 29,
    level: 4
  }
];
